Mise à jour du readme
centralelille/2017-2018-poo4-seance1 pull request #4
Opened 2018-02-22 18:14 UTC by Hercules0402

- Changement du lien travis
- Rajout de section dans le readme

2018-02-22 18:30 UTC, Hercules0402 commented
@loicbourgois : Je rajouterai le fichier LICENSE dans la pull request suivante

2018-02-22 19:06 UTC, loicbourgois requested changes

2018-02-22 19:06 UTC, loicbourgois commented on README.md
> +- [License](#license)
Le lien ne marche pas

2018-02-22 19:06 UTC, loicbourgois commented on README.md
> +## License [![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](LICENSE)
Ce ne serait pas mieux de mettre le badge en haut ?
J'avoue que je ne sais pas comment c'est fait en général. 
Tu peux essayer de voir des exemples de gros repos ?

2018-02-22 19:06 UTC, loicbourgois commented on README.md
> +		- [Create the project](#create-the-project)
Mauvais lien

2018-02-22 19:06 UTC, loicbourgois commented on README.md
> +		- [Persistance Unit](#persistance-unit)
Mauvais lien

2018-02-22 19:29 UTC, Hercules0402 commented
@loicbourgois : J'ai corrigé les liens

2018-02-23 13:49 UTC, loicbourgois approved these changes

2018-02-23 13:49 UTC, merged